name: Fetch BMKG Data
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
          with:
            bun-version: latest
      - name: Install Dependencies
        run: bun install
      - name: Fetch Data from BMKG
        run: bun run index.ts
      - name: Commit and Push Changes
        run: |
          git config --local user.name "FerryAr"
          git config --local user.email "FerryAr@users.noreply.github.com"
          git add .
          git commit -m "Update cuaca BMKG tanggal $(date +'%Y-%m-%d'), jam $(date +'%H:%M:%S') [deploy pages]"
          git push origin main